apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-board
  namespace: postapp
spec:
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: react-board-pod
  template:
    metadata:
      labels:
        app: react-board-pod
    spec:
      containers:
      - name: react-board-container
        image: bellipetti/react-board:8123881f773ed5884a20ce30c07bf7aa8c414dae
        ports:
        - containerPort: 80
